//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ASMXSDMXServiceSoap", Namespace="http://www.imf.org/SDMX")]
public partial class ASMXSDMXService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetMaxSeriesInResultOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDataflowOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetDataStructureOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCompactDataOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetMetadataStructureOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetGenericMetadataOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetServiceVersionOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCodeListOperationCompleted;
    
    /// <remarks/>
    public ASMXSDMXService() {
        this.Url = "http://dataservices.imf.org/sdmx20/SDMX_Web_Service.asmx";
    }
    
    /// <remarks/>
    public event GetMaxSeriesInResultCompletedEventHandler GetMaxSeriesInResultCompleted;
    
    /// <remarks/>
    public event GetDataflowCompletedEventHandler GetDataflowCompleted;
    
    /// <remarks/>
    public event GetDataStructureCompletedEventHandler GetDataStructureCompleted;
    
    /// <remarks/>
    public event GetCompactDataCompletedEventHandler GetCompactDataCompleted;
    
    /// <remarks/>
    public event GetMetadataStructureCompletedEventHandler GetMetadataStructureCompleted;
    
    /// <remarks/>
    public event GetGenericMetadataCompletedEventHandler GetGenericMetadataCompleted;
    
    /// <remarks/>
    public event GetServiceVersionCompletedEventHandler GetServiceVersionCompleted;
    
    /// <remarks/>
    public event GetCodeListCompletedEventHandler GetCodeListCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetMaxSeriesInResult", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public int GetMaxSeriesInResult() {
        object[] results = this.Invoke("GetMaxSeriesInResult", new object[0]);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetMaxSeriesInResult(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetMaxSeriesInResult", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public int EndGetMaxSeriesInResult(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((int)(results[0]));
    }
    
    /// <remarks/>
    public void GetMaxSeriesInResultAsync() {
        this.GetMaxSeriesInResultAsync(null);
    }
    
    /// <remarks/>
    public void GetMaxSeriesInResultAsync(object userState) {
        if ((this.GetMaxSeriesInResultOperationCompleted == null)) {
            this.GetMaxSeriesInResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMaxSeriesInResultOperationCompleted);
        }
        this.InvokeAsync("GetMaxSeriesInResult", new object[0], this.GetMaxSeriesInResultOperationCompleted, userState);
    }
    
    private void OnGetMaxSeriesInResultOperationCompleted(object arg) {
        if ((this.GetMaxSeriesInResultCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetMaxSeriesInResultCompleted(this, new GetMaxSeriesInResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetDataflow", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetDataflow() {
        object[] results = this.Invoke("GetDataflow", new object[0]);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDataflow(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDataflow", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetDataflow(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetDataflowAsync() {
        this.GetDataflowAsync(null);
    }
    
    /// <remarks/>
    public void GetDataflowAsync(object userState) {
        if ((this.GetDataflowOperationCompleted == null)) {
            this.GetDataflowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataflowOperationCompleted);
        }
        this.InvokeAsync("GetDataflow", new object[0], this.GetDataflowOperationCompleted, userState);
    }
    
    private void OnGetDataflowOperationCompleted(object arg) {
        if ((this.GetDataflowCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDataflowCompleted(this, new GetDataflowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetDataStructure", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetDataStructure(System.Xml.XmlElement queryMessage) {
        object[] results = this.Invoke("GetDataStructure", new object[] {
                    queryMessage});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetDataStructure(System.Xml.XmlElement queryMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetDataStructure", new object[] {
                    queryMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetDataStructure(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetDataStructureAsync(System.Xml.XmlElement queryMessage) {
        this.GetDataStructureAsync(queryMessage, null);
    }
    
    /// <remarks/>
    public void GetDataStructureAsync(System.Xml.XmlElement queryMessage, object userState) {
        if ((this.GetDataStructureOperationCompleted == null)) {
            this.GetDataStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataStructureOperationCompleted);
        }
        this.InvokeAsync("GetDataStructure", new object[] {
                    queryMessage}, this.GetDataStructureOperationCompleted, userState);
    }
    
    private void OnGetDataStructureOperationCompleted(object arg) {
        if ((this.GetDataStructureCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetDataStructureCompleted(this, new GetDataStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetCompactData", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetCompactData(System.Xml.XmlElement queryMessage) {
        object[] results = this.Invoke("GetCompactData", new object[] {
                    queryMessage});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCompactData(System.Xml.XmlElement queryMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCompactData", new object[] {
                    queryMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetCompactData(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetCompactDataAsync(System.Xml.XmlElement queryMessage) {
        this.GetCompactDataAsync(queryMessage, null);
    }
    
    /// <remarks/>
    public void GetCompactDataAsync(System.Xml.XmlElement queryMessage, object userState) {
        if ((this.GetCompactDataOperationCompleted == null)) {
            this.GetCompactDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompactDataOperationCompleted);
        }
        this.InvokeAsync("GetCompactData", new object[] {
                    queryMessage}, this.GetCompactDataOperationCompleted, userState);
    }
    
    private void OnGetCompactDataOperationCompleted(object arg) {
        if ((this.GetCompactDataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCompactDataCompleted(this, new GetCompactDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetMetadataStructure", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetMetadataStructure(System.Xml.XmlElement queryMessage) {
        object[] results = this.Invoke("GetMetadataStructure", new object[] {
                    queryMessage});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetMetadataStructure(System.Xml.XmlElement queryMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetMetadataStructure", new object[] {
                    queryMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetMetadataStructure(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetMetadataStructureAsync(System.Xml.XmlElement queryMessage) {
        this.GetMetadataStructureAsync(queryMessage, null);
    }
    
    /// <remarks/>
    public void GetMetadataStructureAsync(System.Xml.XmlElement queryMessage, object userState) {
        if ((this.GetMetadataStructureOperationCompleted == null)) {
            this.GetMetadataStructureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetadataStructureOperationCompleted);
        }
        this.InvokeAsync("GetMetadataStructure", new object[] {
                    queryMessage}, this.GetMetadataStructureOperationCompleted, userState);
    }
    
    private void OnGetMetadataStructureOperationCompleted(object arg) {
        if ((this.GetMetadataStructureCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetMetadataStructureCompleted(this, new GetMetadataStructureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetGenericMetadata", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetGenericMetadata(System.Xml.XmlElement queryMessage) {
        object[] results = this.Invoke("GetGenericMetadata", new object[] {
                    queryMessage});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetGenericMetadata(System.Xml.XmlElement queryMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetGenericMetadata", new object[] {
                    queryMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetGenericMetadata(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetGenericMetadataAsync(System.Xml.XmlElement queryMessage) {
        this.GetGenericMetadataAsync(queryMessage, null);
    }
    
    /// <remarks/>
    public void GetGenericMetadataAsync(System.Xml.XmlElement queryMessage, object userState) {
        if ((this.GetGenericMetadataOperationCompleted == null)) {
            this.GetGenericMetadataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGenericMetadataOperationCompleted);
        }
        this.InvokeAsync("GetGenericMetadata", new object[] {
                    queryMessage}, this.GetGenericMetadataOperationCompleted, userState);
    }
    
    private void OnGetGenericMetadataOperationCompleted(object arg) {
        if ((this.GetGenericMetadataCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetGenericMetadataCompleted(this, new GetGenericMetadataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetServiceVersion", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetServiceVersion() {
        object[] results = this.Invoke("GetServiceVersion", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetServiceVersion(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetServiceVersion", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetServiceVersion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetServiceVersionAsync() {
        this.GetServiceVersionAsync(null);
    }
    
    /// <remarks/>
    public void GetServiceVersionAsync(object userState) {
        if ((this.GetServiceVersionOperationCompleted == null)) {
            this.GetServiceVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceVersionOperationCompleted);
        }
        this.InvokeAsync("GetServiceVersion", new object[0], this.GetServiceVersionOperationCompleted, userState);
    }
    
    private void OnGetServiceVersionOperationCompleted(object arg) {
        if ((this.GetServiceVersionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetServiceVersionCompleted(this, new GetServiceVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imf.org/SDMX/GetCodeList", RequestNamespace="http://www.imf.org/SDMX", ResponseNamespace="http://www.imf.org/SDMX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlElement GetCodeList(System.Xml.XmlElement queryMessage) {
        object[] results = this.Invoke("GetCodeList", new object[] {
                    queryMessage});
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCodeList(System.Xml.XmlElement queryMessage, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCodeList", new object[] {
                    queryMessage}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlElement EndGetCodeList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlElement)(results[0]));
    }
    
    /// <remarks/>
    public void GetCodeListAsync(System.Xml.XmlElement queryMessage) {
        this.GetCodeListAsync(queryMessage, null);
    }
    
    /// <remarks/>
    public void GetCodeListAsync(System.Xml.XmlElement queryMessage, object userState) {
        if ((this.GetCodeListOperationCompleted == null)) {
            this.GetCodeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCodeListOperationCompleted);
        }
        this.InvokeAsync("GetCodeList", new object[] {
                    queryMessage}, this.GetCodeListOperationCompleted, userState);
    }
    
    private void OnGetCodeListOperationCompleted(object arg) {
        if ((this.GetCodeListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCodeListCompleted(this, new GetCodeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetMaxSeriesInResultCompletedEventHandler(object sender, GetMaxSeriesInResultCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetMaxSeriesInResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetMaxSeriesInResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public int Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((int)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetDataflowCompletedEventHandler(object sender, GetDataflowCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDataflowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDataflowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetDataStructureCompletedEventHandler(object sender, GetDataStructureCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetDataStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetDataStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetCompactDataCompletedEventHandler(object sender, GetCompactDataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCompactDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCompactDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetMetadataStructureCompletedEventHandler(object sender, GetMetadataStructureCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetMetadataStructureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetMetadataStructureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetGenericMetadataCompletedEventHandler(object sender, GetGenericMetadataCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetGenericMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetGenericMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetServiceVersionCompletedEventHandler(object sender, GetServiceVersionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetServiceVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetServiceVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void GetCodeListCompletedEventHandler(object sender, GetCodeListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCodeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetCodeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlElement Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlElement)(this.results[0]));
        }
    }
}
