//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImfService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.imf.org/SDMX", ConfigurationName="ImfService.ASMXSDMXServiceSoap")]
    public interface ASMXSDMXServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetMaxSeriesInResult", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetMaxSeriesInResultAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetDataflow", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetDataflowResponse> GetDataflowAsync(ImfService.GetDataflowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetDataStructure", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetDataStructureResponse> GetDataStructureAsync(ImfService.GetDataStructureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetCompactData", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetCompactDataResponse> GetCompactDataAsync(ImfService.GetCompactDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetMetadataStructure", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetMetadataStructureResponse> GetMetadataStructureAsync(ImfService.GetMetadataStructureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetGenericMetadata", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetGenericMetadataResponse> GetGenericMetadataAsync(ImfService.GetGenericMetadataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetServiceVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetServiceVersionResponse> GetServiceVersionAsync(ImfService.GetServiceVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imf.org/SDMX/GetCodeList", ReplyAction="*")]
        System.Threading.Tasks.Task<ImfService.GetCodeListResponse> GetCodeListAsync(ImfService.GetCodeListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataflowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataflow", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetDataflowRequestBody Body;
        
        public GetDataflowRequest()
        {
        }
        
        public GetDataflowRequest(ImfService.GetDataflowRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataflowRequestBody
    {
        
        public GetDataflowRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataflowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataflowResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetDataflowResponseBody Body;
        
        public GetDataflowResponse()
        {
        }
        
        public GetDataflowResponse(ImfService.GetDataflowResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetDataflowResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataflowResult;
        
        public GetDataflowResponseBody()
        {
        }
        
        public GetDataflowResponseBody(System.Xml.XmlElement GetDataflowResult)
        {
            this.GetDataflowResult = GetDataflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStructureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStructure", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetDataStructureRequestBody Body;
        
        public GetDataStructureRequest()
        {
        }
        
        public GetDataStructureRequest(ImfService.GetDataStructureRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetDataStructureRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement queryMessage;
        
        public GetDataStructureRequestBody()
        {
        }
        
        public GetDataStructureRequestBody(System.Xml.XmlElement queryMessage)
        {
            this.queryMessage = queryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataStructureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataStructureResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetDataStructureResponseBody Body;
        
        public GetDataStructureResponse()
        {
        }
        
        public GetDataStructureResponse(ImfService.GetDataStructureResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetDataStructureResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetDataStructureResult;
        
        public GetDataStructureResponseBody()
        {
        }
        
        public GetDataStructureResponseBody(System.Xml.XmlElement GetDataStructureResult)
        {
            this.GetDataStructureResult = GetDataStructureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompactDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompactData", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetCompactDataRequestBody Body;
        
        public GetCompactDataRequest()
        {
        }
        
        public GetCompactDataRequest(ImfService.GetCompactDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetCompactDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement queryMessage;
        
        public GetCompactDataRequestBody()
        {
        }
        
        public GetCompactDataRequestBody(System.Xml.XmlElement queryMessage)
        {
            this.queryMessage = queryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompactDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCompactDataResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetCompactDataResponseBody Body;
        
        public GetCompactDataResponse()
        {
        }
        
        public GetCompactDataResponse(ImfService.GetCompactDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetCompactDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetCompactDataResult;
        
        public GetCompactDataResponseBody()
        {
        }
        
        public GetCompactDataResponseBody(System.Xml.XmlElement GetCompactDataResult)
        {
            this.GetCompactDataResult = GetCompactDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataStructureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadataStructure", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetMetadataStructureRequestBody Body;
        
        public GetMetadataStructureRequest()
        {
        }
        
        public GetMetadataStructureRequest(ImfService.GetMetadataStructureRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetMetadataStructureRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement queryMessage;
        
        public GetMetadataStructureRequestBody()
        {
        }
        
        public GetMetadataStructureRequestBody(System.Xml.XmlElement queryMessage)
        {
            this.queryMessage = queryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetadataStructureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetadataStructureResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetMetadataStructureResponseBody Body;
        
        public GetMetadataStructureResponse()
        {
        }
        
        public GetMetadataStructureResponse(ImfService.GetMetadataStructureResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetMetadataStructureResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetMetadataStructureResult;
        
        public GetMetadataStructureResponseBody()
        {
        }
        
        public GetMetadataStructureResponseBody(System.Xml.XmlElement GetMetadataStructureResult)
        {
            this.GetMetadataStructureResult = GetMetadataStructureResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenericMetadataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenericMetadata", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetGenericMetadataRequestBody Body;
        
        public GetGenericMetadataRequest()
        {
        }
        
        public GetGenericMetadataRequest(ImfService.GetGenericMetadataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetGenericMetadataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement queryMessage;
        
        public GetGenericMetadataRequestBody()
        {
        }
        
        public GetGenericMetadataRequestBody(System.Xml.XmlElement queryMessage)
        {
            this.queryMessage = queryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGenericMetadataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGenericMetadataResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetGenericMetadataResponseBody Body;
        
        public GetGenericMetadataResponse()
        {
        }
        
        public GetGenericMetadataResponse(ImfService.GetGenericMetadataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetGenericMetadataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetGenericMetadataResult;
        
        public GetGenericMetadataResponseBody()
        {
        }
        
        public GetGenericMetadataResponseBody(System.Xml.XmlElement GetGenericMetadataResult)
        {
            this.GetGenericMetadataResult = GetGenericMetadataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceVersion", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetServiceVersionRequestBody Body;
        
        public GetServiceVersionRequest()
        {
        }
        
        public GetServiceVersionRequest(ImfService.GetServiceVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetServiceVersionRequestBody
    {
        
        public GetServiceVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetServiceVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetServiceVersionResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetServiceVersionResponseBody Body;
        
        public GetServiceVersionResponse()
        {
        }
        
        public GetServiceVersionResponse(ImfService.GetServiceVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetServiceVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetServiceVersionResult;
        
        public GetServiceVersionResponseBody()
        {
        }
        
        public GetServiceVersionResponseBody(string GetServiceVersionResult)
        {
            this.GetServiceVersionResult = GetServiceVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCodeListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCodeList", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetCodeListRequestBody Body;
        
        public GetCodeListRequest()
        {
        }
        
        public GetCodeListRequest(ImfService.GetCodeListRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetCodeListRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement queryMessage;
        
        public GetCodeListRequestBody()
        {
        }
        
        public GetCodeListRequestBody(System.Xml.XmlElement queryMessage)
        {
            this.queryMessage = queryMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCodeListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCodeListResponse", Namespace="http://www.imf.org/SDMX", Order=0)]
        public ImfService.GetCodeListResponseBody Body;
        
        public GetCodeListResponse()
        {
        }
        
        public GetCodeListResponse(ImfService.GetCodeListResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imf.org/SDMX")]
    public partial class GetCodeListResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.XmlElement GetCodeListResult;
        
        public GetCodeListResponseBody()
        {
        }
        
        public GetCodeListResponseBody(System.Xml.XmlElement GetCodeListResult)
        {
            this.GetCodeListResult = GetCodeListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ASMXSDMXServiceSoapChannel : ImfService.ASMXSDMXServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ASMXSDMXServiceSoapClient : System.ServiceModel.ClientBase<ImfService.ASMXSDMXServiceSoap>, ImfService.ASMXSDMXServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ASMXSDMXServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ASMXSDMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ASMXSDMXServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ASMXSDMXServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ASMXSDMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ASMXSDMXServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ASMXSDMXServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ASMXSDMXServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> GetMaxSeriesInResultAsync()
        {
            return base.Channel.GetMaxSeriesInResultAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetDataflowResponse> ImfService.ASMXSDMXServiceSoap.GetDataflowAsync(ImfService.GetDataflowRequest request)
        {
            return base.Channel.GetDataflowAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetDataflowResponse> GetDataflowAsync()
        {
            ImfService.GetDataflowRequest inValue = new ImfService.GetDataflowRequest();
            inValue.Body = new ImfService.GetDataflowRequestBody();
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetDataflowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetDataStructureResponse> ImfService.ASMXSDMXServiceSoap.GetDataStructureAsync(ImfService.GetDataStructureRequest request)
        {
            return base.Channel.GetDataStructureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetDataStructureResponse> GetDataStructureAsync(System.Xml.XmlElement queryMessage)
        {
            ImfService.GetDataStructureRequest inValue = new ImfService.GetDataStructureRequest();
            inValue.Body = new ImfService.GetDataStructureRequestBody();
            inValue.Body.queryMessage = queryMessage;
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetDataStructureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetCompactDataResponse> ImfService.ASMXSDMXServiceSoap.GetCompactDataAsync(ImfService.GetCompactDataRequest request)
        {
            return base.Channel.GetCompactDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetCompactDataResponse> GetCompactDataAsync(System.Xml.XmlElement queryMessage)
        {
            ImfService.GetCompactDataRequest inValue = new ImfService.GetCompactDataRequest();
            inValue.Body = new ImfService.GetCompactDataRequestBody();
            inValue.Body.queryMessage = queryMessage;
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetCompactDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetMetadataStructureResponse> ImfService.ASMXSDMXServiceSoap.GetMetadataStructureAsync(ImfService.GetMetadataStructureRequest request)
        {
            return base.Channel.GetMetadataStructureAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetMetadataStructureResponse> GetMetadataStructureAsync(System.Xml.XmlElement queryMessage)
        {
            ImfService.GetMetadataStructureRequest inValue = new ImfService.GetMetadataStructureRequest();
            inValue.Body = new ImfService.GetMetadataStructureRequestBody();
            inValue.Body.queryMessage = queryMessage;
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetMetadataStructureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetGenericMetadataResponse> ImfService.ASMXSDMXServiceSoap.GetGenericMetadataAsync(ImfService.GetGenericMetadataRequest request)
        {
            return base.Channel.GetGenericMetadataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetGenericMetadataResponse> GetGenericMetadataAsync(System.Xml.XmlElement queryMessage)
        {
            ImfService.GetGenericMetadataRequest inValue = new ImfService.GetGenericMetadataRequest();
            inValue.Body = new ImfService.GetGenericMetadataRequestBody();
            inValue.Body.queryMessage = queryMessage;
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetGenericMetadataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetServiceVersionResponse> ImfService.ASMXSDMXServiceSoap.GetServiceVersionAsync(ImfService.GetServiceVersionRequest request)
        {
            return base.Channel.GetServiceVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetServiceVersionResponse> GetServiceVersionAsync()
        {
            ImfService.GetServiceVersionRequest inValue = new ImfService.GetServiceVersionRequest();
            inValue.Body = new ImfService.GetServiceVersionRequestBody();
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetServiceVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ImfService.GetCodeListResponse> ImfService.ASMXSDMXServiceSoap.GetCodeListAsync(ImfService.GetCodeListRequest request)
        {
            return base.Channel.GetCodeListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ImfService.GetCodeListResponse> GetCodeListAsync(System.Xml.XmlElement queryMessage)
        {
            ImfService.GetCodeListRequest inValue = new ImfService.GetCodeListRequest();
            inValue.Body = new ImfService.GetCodeListRequestBody();
            inValue.Body.queryMessage = queryMessage;
            return ((ImfService.ASMXSDMXServiceSoap)(this)).GetCodeListAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ASMXSDMXServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ASMXSDMXServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ASMXSDMXServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://dataservices.imf.org/sdmx20/SDMX_Web_Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ASMXSDMXServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://dataservices.imf.org/sdmx20/SDMX_Web_Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ASMXSDMXServiceSoap,
            
            ASMXSDMXServiceSoap12,
        }
    }
}
