set identity_insert Unit on
insert into Unit
	([Id], [Name])
values
	(1, 'mark'),
	(2, 'daler'),
	(3, 'daler coppermynt'),
	(4, 'daler silvermynt'),
	(5, 'riksdaler'),
	(6, 'kronor'),
	(7, 'öre'),
	(8, 'liter'),
	(9, 'barrel'),
	(10, 'ship pound'),
	(11, 'gram'),
	(12, 'last of 45 hL'),
	(13, 'skeppund of 136 kg'),
	(14, 'famn of 3.14 cubic meters'),
	(15, 'last of 2,000 kilograms'),
	(16, 'lispund')
go

insert into Unit 
	([Id], [Name]) 
values 
	(17, 'mark per last of 45 hl'),
	(18, 'daler kopparmynt per barrel'),
	(19, 'kronor per 100 liters'),
	(20, 'mark per barrel'),
	(21, 'mark per last of 45 hl'),
	(22, 'mark per barrel'),
	(23, 'kronor per 100 liters'),
	(24, 'daler silvermynt per barrel'),
	(25, 'mark per last of 45 hl'),
	(26, 'mark per barrel'),
	(27, 'kronor per 100 liters'),
	(28, 'öre per barrel'),
	(29, 'mark per barrel'),
	(30, 'daler silvermynt per barrel'),
	(31, 'kronor per 100 liters'),
	(32, 'grams of silver per barrel'),
	(33, 'mark per 1,000'),
	(34, 'daler kopparmynt per 1,000'),
	(35, 'kronor per 1,000'),
	(36, 'mark per barrel'),
	(37, 'mark per lispund'),
	(38, 'daler kopparmynt per lispund'),
	(39, 'grams of silver per barrel'),
	(40, 'kronor per kilogram'),
	(41, 'mark per ship pound'),
	(42, 'daler kopparmynt per ship pound'),
	(43, 'mark per ship pound'),
	(44, 'riksdaler per ship pound'),
	(45, 'grams of silver per ship pound'),
	(46, 'riksdaler banco per skeppund of 136 kg '),
	(47, 'kronor per 100 kilograms'),
	(48, 'kronor per 100 kilograms'),
	(49, 'kronor per 100 kilograms'),
	(50, 'mark per famn of 3.14 cubic meters'),
	(51, 'daler kopparmynt per famn of 3.14 cubic meters'),
	(52, 'daler kopparmynt per cubic meter'),
	(53, 'kronor per cubic meter'),
	(54, 'mark per ship pound'),
	(55, 'daler silvermynt per ship pound'),
	(56, 'daler kopparmynt per lispund'),
	(57, 'kronor per kilogram'),
	(58, 'mark per last of 2,000 kilograms'),
	(59, 'mark per skeppund'),
	(60, 'daler kopparmynt per skeppund'),
	(61, 'kronor per 100 kilograms'),
	(62, 'kronor per 100 kilograms'),
	(63, 'öre per animal'),
	(64, 'daler kopparmynt per animal'),
	(65, 'kronor per animal'),
	(66, 'öre per barrel'),
	(67, 'mark per barrel'),
	(68, 'daler kopparmynt per barrel'),
	(69, 'kronor per barrel'),
	(70, 'kronor per 100 liters'),
	(71, 'kronor per 100 kilogram'),
	(72, 'öre per lispund'),
	(73, 'litres'),
	(74, 'litres'),
	(75, 'kilograms'),
	(76, 'kilograms'),
	(77, 'kilograms'),
	(78, 'kilograms'),
	(79, 'grams'),
	(80, 'grams'),
	(81, 'grams'),
	(82, 'grams'),
	(83, 'grams'),
	(84, 'grams')